name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  auto-tag-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Pixiv.js
          draft: false
          prerelease: false
          generate_release_notes: true
